---@class HighlightModule
local M = {}

---@param p ThemeColors
---@return HighlightGroups
M.get = function(p)
	local e = p.editor
	local d = p.diagnostic
	local dbg = p.debug

	return {
		Normal = { fg = e.fg, bg = e.bg },
		NormalNC = { fg = e.fg, bg = e.bg },
		NormalFloat = { fg = e.fg, bg = e.bg },
		FloatBorder = { fg = e.border, bg = e.bg },
		FloatTitle = { fg = e.bright, bg = e.bg, bold = true },
		FloatFooter = { fg = e.subtle, bg = e.bg },
		ColorColumn = { bg = e.surface },
		Conceal = { fg = e.dim },
		Cursor = { fg = e.bg, bg = e.fg },
		lCursor = { fg = e.bg, bg = e.fg },
		CursorIM = { fg = e.bg, bg = e.fg },
		CursorColumn = { bg = e.surface },
		CursorLine = { bg = e.surface },
		CursorLineNr = { fg = e.bright, bold = true },
		LineNr = { fg = e.dim },
		Directory = { fg = d.hint },
		DebugBorder = { fg = dbg.border },
		DebugHeader = { fg = dbg.header, bold = true },
		DebugInfo = { fg = dbg.info },
		DebugLabel = { fg = dbg.label },
		DebugMuted = { fg = dbg.muted, italic = true },
		DebugOk = { fg = dbg.ok, bold = true },
		DebugTabActive = { fg = dbg.tabActiveFg, bg = dbg.tabActiveBg, bold = true },
		DebugTabActiveSep = { fg = dbg.tabActiveBg, bg = e.bg },
		DebugTabFill = { bg = e.bg },
		DebugTabInactive = { fg = dbg.tabInactiveFg, bg = dbg.tabInactiveBg },
		DebugTabInactiveSep = { fg = dbg.tabInactiveBg, bg = e.bg },
		DebugValue = { fg = dbg.value },
		DebugWarn = { fg = dbg.warn, bold = true },
		EndOfBuffer = { fg = e.bg },
		ErrorMsg = { fg = d.error, bold = true },
		WarningMsg = { fg = d.warn },
		MoreMsg = { fg = d.ok },
		ModeMsg = { fg = e.fg, bold = true },
		Folded = { fg = e.comment, bg = e.surface },
		FoldColumn = { fg = e.dim },
		SignColumn = { bg = e.bg },
		IncSearch = { fg = e.bg, bg = d.warn },
		CurSearch = { fg = e.bg, bg = d.warn, bold = true },
		Search = { fg = e.selectionFg, bg = e.selectionBg },
		MatchParen = { fg = d.warn, bold = true, underline = true },
		NonText = { fg = e.dim },
		Pmenu = { fg = e.subtle, bg = e.surface },
		PmenuSel = { fg = e.selectionFg, bg = e.selectionBg },
		PmenuSbar = { bg = e.surface },
		PmenuThumb = { bg = e.dim },
		Question = { fg = d.ok },
		QuickFixLine = { bg = e.surface, bold = true },
		SpecialKey = { fg = e.dim },
		SpellBad = { sp = d.error, undercurl = true },
		SpellCap = { sp = d.warn, undercurl = true },
		SpellLocal = { sp = d.info, undercurl = true },
		SpellRare = { sp = p.syntax.constant, undercurl = true },
		StatusLine = { fg = p.status.fg, bg = p.status.bg },
		StatusLineNC = { fg = p.status.inactive, bg = e.bg },
		StatusLineTerm = { fg = p.status.fg, bg = p.status.bg },
		StatusLineTermNC = { fg = p.status.inactive, bg = e.bg },
		Substitute = { fg = e.bg, bg = d.error },
		TabLine = { fg = e.dim, bg = e.bg },
		TabLineFill = { bg = e.bg },
		TabLineSel = { fg = e.bright, bg = e.surface, bold = true },
		Title = { fg = e.bright, bold = true },
		Visual = { bg = e.selectionBg },
		VisualNOS = { bg = e.selectionBg },
		Whitespace = { fg = e.dim },
		WildMenu = { fg = e.bg, bg = d.info, bold = true },
		WinBar = { fg = e.subtle, bg = e.surface },
		WinBarNC = { fg = e.comment, bg = e.surface },
		WinSeparator = { fg = e.dim },
	}
end

return M
