---@class HighlightModule
local M = {}

---@param p ThemePalette
---@return HighlightGroups
M.get = function(p)
	return {
		Normal = { fg = p.base, bg = p.black },
		NormalNC = { fg = p.base, bg = p.black },
		NormalFloat = { fg = p.base, bg = p.black },
		FloatBorder = { fg = p.bright, bg = p.black },
		FloatTitle = { fg = p.bright, bg = p.black, bold = true },
		FloatFooter = { fg = p.comment, bg = p.black },
		ColorColumn = { bg = p.surface },
		Conceal = { fg = p.dim },
		Cursor = { fg = p.black, bg = p.base },
		lCursor = { fg = p.black, bg = p.base },
		CursorIM = { fg = p.black, bg = p.base },
		CursorColumn = { bg = p.surface },
		CursorLine = { bg = p.surface },
		CursorLineNr = { fg = p.bright, bold = true },
		LineNr = { fg = p.dim },
		Directory = { fg = p.blue },
		EndOfBuffer = { fg = p.black },
		ErrorMsg = { fg = p.red, bold = true },
		WarningMsg = { fg = p.yellow },
		MoreMsg = { fg = p.green },
		ModeMsg = { fg = p.base, bold = true },
		Folded = { fg = p.comment, bg = p.surface },
		FoldColumn = { fg = p.dim },
		SignColumn = { bg = p.black },
		IncSearch = { fg = p.black, bg = p.yellow_bright },
		CurSearch = { fg = p.black, bg = p.yellow_bright, bold = true },
		Search = { fg = p.black, bg = p.yellow },
		MatchParen = { fg = p.yellow_bright, bold = true, underline = true },
		NonText = { fg = p.dim },
		Pmenu = { fg = p.base, bg = p.surface },
		PmenuSel = { fg = p.black, bg = p.base },
		PmenuSbar = { bg = p.surface },
		PmenuThumb = { bg = p.dim },
		Question = { fg = p.green },
		QuickFixLine = { bg = p.surface, bold = true },
		SpecialKey = { fg = p.dim },
		SpellBad = { sp = p.red, undercurl = true },
		SpellCap = { sp = p.yellow, undercurl = true },
		SpellLocal = { sp = p.cyan, undercurl = true },
		SpellRare = { sp = p.magenta, undercurl = true },
		StatusLine = { fg = p.base, bg = p.surface },
		StatusLineNC = { fg = p.dim, bg = p.black },
		StatusLineTerm = { fg = p.base, bg = p.surface },
		StatusLineTermNC = { fg = p.dim, bg = p.black },
		Substitute = { fg = p.black, bg = p.red },
		TabLine = { fg = p.dim, bg = p.black },
		TabLineFill = { bg = p.black },
		TabLineSel = { fg = p.bright, bg = p.surface, bold = true },
		Title = { fg = p.bright, bold = true },
		Visual = { bg = p.dim },
		VisualNOS = { bg = p.dim },
		Whitespace = { fg = p.dim },
		WildMenu = { fg = p.black, bg = p.cyan, bold = true },
		WinBar = { fg = p.base, bg = p.surface },
		WinBarNC = { fg = p.comment, bg = p.surface },
		WinSeparator = { fg = p.dim },
	}
end

return M
