local palette = require("config.theme.palette")
local p, a = palette.p, palette.a

local M = {}

---@return HighlightGroups
M.get = function()
	return {
		Normal = { fg = p.foreground.base, bg = p.background.base },
		NormalNC = { fg = p.foreground.base, bg = p.background.base },
		NormalFloat = { fg = p.foreground.base, bg = p.background.variant },
		FloatBorder = { fg = p.foreground.base, bg = p.background.base },
		FloatTitle = { fg = p.foreground.variant, bg = p.background.base, bold = true },
		FloatFooter = { fg = p.accent.base, bg = p.background.base },
		ColorColumn = { bg = p.background.variant },
		Conceal = { fg = p.dim },
		Cursor = { fg = p.background.base, bg = p.foreground.base },
		lCursor = { fg = p.background.base, bg = p.foreground.base },
		CursorIM = { fg = p.background.base, bg = p.foreground.base },
		CursorColumn = { bg = p.background.variant },
		CursorLine = { bg = p.background.variant },
		CursorLineNr = { fg = p.foreground.variant, bold = true },
		LineNr = { fg = p.dim },
		Directory = { fg = p.surface.base },
		DebugBorder = { fg = p.background.variant },
		DebugHeader = { fg = p.accent.base, bold = true },
		DebugInfo = { fg = a.info },
		DebugLabel = { fg = p.accent.base },
		DebugMuted = { fg = p.dim, italic = true },
		DebugOk = { fg = a.success, bold = true },
		DebugTabActive = { fg = p.background.base, bg = p.accent.base, bold = true },
		DebugTabActiveSep = { fg = p.accent.base, bg = p.background.base },
		DebugTabFill = { bg = p.background.base },
		DebugTabInactive = { fg = p.dim, bg = p.background.variant },
		DebugTabInactiveSep = { fg = p.background.variant, bg = p.background.base },
		DebugValue = { fg = p.foreground.base },
		DebugWarn = { fg = a.warn, bold = true },
		EndOfBuffer = { fg = p.background.base },
		ErrorMsg = { fg = a.error, bold = true },
		WarningMsg = { fg = a.warn },
		MoreMsg = { fg = a.success },
		ModeMsg = { fg = p.foreground.base, bold = true },
		Folded = { fg = p.dim, bg = p.background.variant },
		FoldColumn = { fg = p.dim },
		SignColumn = { bg = p.background.base },
		IncSearch = { fg = p.background.base, bg = a.warn },
		CurSearch = { fg = p.background.base, bg = a.warn, bold = true },
		Search = { fg = p.background.variant, bg = p.accent.base },
		MatchParen = { fg = a.warn, bold = true, underline = true },
		NonText = { fg = p.dim },
		Pmenu = { fg = p.accent.base, bg = p.background.variant },
		PmenuSel = { fg = p.background.variant, bg = p.accent.base },
		PmenuSbar = { bg = p.background.variant },
		PmenuThumb = { bg = p.dim },
		Question = { fg = a.success },
		QuickFixLine = { bg = p.background.variant, bold = true },
		SpecialKey = { fg = p.dim },
		SpellBad = { sp = a.error, undercurl = true },
		SpellCap = { sp = a.warn, undercurl = true },
		SpellLocal = { sp = a.info, undercurl = true },
		SpellRare = { sp = p.accent.variant, undercurl = true },
		StatusLine = { fg = p.accent.base, bg = p.background.variant },
		StatusLineNC = { fg = p.dim, bg = p.background.base },
		StatusLineTerm = { fg = p.accent.base, bg = p.background.variant },
		StatusLineTermNC = { fg = p.dim, bg = p.background.base },
		Substitute = { fg = p.background.base, bg = a.error },
		TabLine = { fg = p.dim, bg = p.background.base },
		TabLineFill = { bg = p.background.base },
		TabLineSel = { fg = p.foreground.variant, bg = p.background.variant, bold = true },
		Title = { fg = p.foreground.variant, bold = true },
		Visual = { bg = p.accent.base, fg = p.background.variant },
		VisualNOS = { bg = p.accent.base },
		Whitespace = { fg = p.dim },
		WildMenu = { fg = p.background.base, bg = a.info, bold = true },
		WinBar = { fg = p.accent.base, bg = p.background.variant },
		WinBarNC = { fg = p.dim, bg = p.background.variant },
		WinSeparator = { fg = p.dim },
	}
end

return M
