theme: angst
load_user_themes: true
theme_directory: "/home/joao/.config/posting/themes"
layout: horizontal
response:
  prettify_json: true
  show_size_and_time: true
heading:
  show_host: false
  show_version: false
text_input:
  blinking_cursor: false
collection_browser:
  show_on_startup: true

