---
creation_rules:
  - path_regex: hosts/servers/.*/secrets\.yaml$
    age: |
      # Add your server age public keys below.
      # age1...
  - path_regex: hosts/personal/.*/secrets\.yaml$
    age: |
      age17yz8euqt9y33l5ypyeeg54auar65wv2wdu2sxcmtx3t8l0dzjvwq3v7zl9
  - path_regex: hosts/vm/secrets\.yaml$
    age: |
      age17yz8euqt9y33l5ypyeeg54auar65wv2wdu2sxcmtx3t8l0dzjvwq3v7zl9
