background           = 222222
foreground           = c2c2b0
cursor-color         = c2c2b0
selection-background = 8c8c7a
selection-foreground = c2c2b0
palette = 0=#222222
palette = 1=#b84a4a
palette = 2=#608f60
palette = 3=#c4904a
palette = 4=#6290a0
palette = 5=#a07aaa
palette = 6=#5faa8e
palette = 7=#c2c2b0
palette = 8=#5e5e5e
palette = 9=#b84a4a
palette = 10=#608f60
palette = 11=#c4904a
palette = 12=#6290a0
palette = 13=#a07aaa
palette = 14=#5faa8e
palette = 15=#c2c2b0