background           = f2ecbc
foreground           = 545464
cursor-color         = 545464
selection-background = c84053
selection-foreground = 545464
palette = 0=#e5dfae
palette = 1=#597b75
palette = 2=#6f894e
palette = 3=#c84053
palette = 4=#77713f
palette = 5=#b35b79
palette = 6=#4d699b
palette = 7=#545464
palette = 8=#597b75
palette = 9=#597b75
palette = 10=#6f894e
palette = 11=#c84053
palette = 12=#77713f
palette = 13=#b35b79
palette = 14=#4d699b
palette = 15=#545464

