[mode]
normal_main = { bg = "#545464", fg = "#e5dfae", bold = true }
normal_alt  = { fg = "#545464", bg = "#e5dfae" }

[filetype]
rules = [
    { mime = "image/*", fg = "#6f894e" },
    { mime = "video/*", fg = "#b35b79" },
    { mime = "inode/empty", fg = "#597b75" },
    { url = "*/", fg = "#77713f" }
]

[overall]
bg = "#f2ecbc"

