[mode]
normal_main = { bg = "#d7c483", fg = "#000000", bold = true }
normal_alt  = { fg = "#d7c483", bg = "#000000" }

[filetype]
rules = [
    { mime = "image/*", fg = "#5f875f" },
    { mime = "video/*", fg = "#bb7744" },
    { mime = "inode/empty", fg = "#685742" },
    { url = "*/", fg = "#78824b" }
]

[overall]
bg = "#222222"

