[mode]
normal_main = { bg = "#c8c093", fg = "#211f1f", bold = true }
normal_alt  = { fg = "#c8c093", bg = "#211f1f" }

[filetype]
rules = [
    { mime = "image/*", fg = "#8a9a7b" },        
    { mime = "video/*", fg = "#a292a3" },       
    { mime = "inode/empty", fg = "#2d4f67" },  
    { url = "*/", fg = "#8ba4b0" }            
]

[overall]
bg = "#181616"
