format = """
$username$hostname $env_var$directory $git_branch$git_status$nix_shell$buf$bun$c$cpp$cmake$cobol$crystal$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$fortran$gleam$golang$gradle$haskell$haxe$helm$java$julia$kotlin$lua$maven$meson$mojo$nim$nodejs$ocaml$odin$opa$perl$php$pulumi$python$r$raku$ruby$rust$scala$solidity$spack$sphinx$sql$svelte$swift$terraform$typst$vagrant$vala$verilog$vlang$zig

"""

add_newline = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold #b36d43"
read_only = " RO"
read_only_style = "bold #ff3333"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "*[$branch]($style)"
style = "#685742"
symbol = ""

[git_status]
format = ' [\[$all_status$ahead_behind\]]($style) '
style = "#ffaa00"
conflicted = "!"
ahead = "+"
behind = "-"
diverged = "+-"
untracked = "?"
stashed = "*"
modified = "~"
staged = "+"
renamed = "r"
deleted = "x"

[nix_shell]
format = "[$symbol$state( $name)]($style) "
symbol = " "
style = "#685742"

[username]
format = "[$user]($style)"
style_user = "bold #5f7a5f"
style_root = "bold #ff3333"
show_always = true

[hostname]
format = "[@$hostname]($style)"
style = "bold #5f7a5f"
ssh_only = true

[daml]
format = "[$symbol](#BFCAA3)[($version)]($style) "
symbol = " "
style = "#685742"

[buf]
format = "[$symbol](#C8916C)[($version)]($style) "
symbol = " "
style = "#685742"

[bun]
format = "[$symbol](#F9C1B1)[($version)]($style) "
symbol = " "
style = "#685742"

[c]
format = "[$symbol](#599BF5)[($version)]($style) "
symbol = " "
style = "#685742"

[cmake]
format = "[$symbol](#75AADB)[($version)]($style) "
symbol = " "
style = "#685742"

[cobol]
format = "[$symbol](#005CA5)[($version)]($style) "
symbol = "⚙ "
style = "#685742"

[cpp]
format = "[$symbol](#599BF5)[($version)]($style) "
symbol = " "
style = "#685742"

[crystal]
format = "[$symbol](#FAE2AF)[($version)]($style) "
symbol = " "
style = "#685742"

[dart]
format = "[$symbol](#66B9F0)[($version)]($style) "
symbol = " "
style = "#685742"

[deno]
format = "[$symbol](#A7D192)[($version)]($style) "
symbol = " "
style = "#685742"

[dotnet]
format = "[$symbol](#A77EDB)[($version)]($style) "
symbol = " "
style = "#685742"

[elixir]
format = "[$symbol](#A076B5)[($version)]($style) "
symbol = " "
style = "#685742"

[elm]
format = "[$symbol](#5CC1D5)[($version)]($style) "
symbol = " "
style = "#685742"

[erlang]
format = "[$symbol](#CA274A)[($version)]($style) "
symbol = " "
style = "#685742"

[fennel]
format = "[$symbol](#C2D48B)[($version)]($style) "
symbol = " "
style = "#685742"

[fortran]
format = "[$symbol](#815AA4)[($version)]($style) "
symbol = "󱈚 "
style = "#685742"

[gleam]
format = "[$symbol](#F6C8B5)[($version)]($style) "
symbol = " "
style = "#685742"

[golang]
format = "[$symbol](#6AD0E0)[($version)]($style) "
symbol = " "
style = "#685742"

[gradle]
format = "[$symbol](#86CD82)[($version)]($style) "
symbol = " "
style = "#685742"

[haskell]
format = "[$symbol](#9B6CCE)[($version)]($style) "
symbol = " "
style = "#685742"

[haxe]
format = "[$symbol](#EAA56F)[($version)]($style) "
symbol = " "
style = "#685742"

[helm]
format = "[$symbol](#5880BE)[($version)]($style) "
symbol = "⎈ "
style = "#685742"

[java]
format = "[$symbol](#E76F54)[($version)]($style) "
symbol = " "
style = "#685742"

[julia]
format = "[$symbol](#3EB886)[($version)]($style) "
symbol = " "
style = "#685742"

[kotlin]
format = "[$symbol](#7B60B5)[($version)]($style) "
symbol = " "
style = "#685742"

[lua]
format = "[$symbol](#519ABC)[($version)]($style) "
symbol = " "
style = "#685742"

[maven]
format = "[$symbol](#C64A36)[($version)]($style) "
symbol = " "
style = "#685742"

[meson]
format = "[$symbol](#6DB48D)[($version)]($style) "
symbol = "󰔿 "
style = "#685742"

[mojo]
format = "[$symbol](#EAA56F)[($version)]($style) "
symbol = " "
style = "#685742"

[nim]
format = "[$symbol](#C9D17E)[($version)]($style) "
symbol = " "
style = "#685742"

[nodejs]
format = "[$symbol](#6DA55F)[($version)]($style) "
symbol = " "
style = "#685742"

[ocaml]
format = "[$symbol](#E67E4C)[($version)]($style) "
symbol = " "
style = "#685742"

[odin]
format = "[$symbol](#3884D9)[($version)]($style) "
symbol = " "
style = "#685742"

[opa]
format = "[$symbol](#87D0D0)[($version)]($style) "
symbol = " "
style = "#685742"

[perl]
format = "[$symbol](#A0BADA)[($version)]($style) "
symbol = " "
style = "#685742"

[php]
format = "[$symbol](#7C8FC3)[($version)]($style) "
symbol = " "
style = "#685742"

[pulumi]
format = "[$symbol](#C17776)[($version)]($style) "
symbol = " "
style = "#685742"

[python]
format = "[$symbol](#F5D87B)[($version)]($style) "
symbol = " "
style = "#685742"

[r]
format = "[$symbol](#3A80B9)[($version)]($style) "
symbol = "󰟔 "
style = "#685742"

[raku]
format = "[$symbol](#B5C0D1)[($version)]($style) "
symbol = " "
style = "#685742"

[ruby]
format = "[$symbol](#C7383E)[($version)]($style) "
symbol = " "
style = "#685742"

[rust]
format = "[$symbol](#E8AF4C)[($version)]($style) "
symbol = " "
style = "#685742"

[scala]
format = "[$symbol](#C53B2D)[($version)]($style) "
symbol = " "
style = "#685742"

[solidity]
format = "[$symbol](#C0C9D7)[($version)]($style) "
symbol = "ﲹ "
style = "#685742"

[spack]
format = "[$symbol](#66A1B7)[($version)]($style) "
symbol = " "
style = "#685742"

[sphinx]
format = "[$symbol](#97BBD9)[($version)]($style) "
symbol = " "
style = "#685742"

[sql]
format = "[$symbol](#B3BAC5)[($version)]($style) "
symbol = " "
style = "#685742"

[svelte]
format = "[$symbol](#CF897B)[($version)]($style) "
symbol = " "
style = "#685742"

[swift]
format = "[$symbol](#E77656)[($version)]($style) "
symbol = "�刀 "
style = "#685742"

[terraform]
format = "[$symbol](#7C91BE)[($version)]($style) "
symbol = " "
style = "#685742"

[typst]
format = "[$symbol](#435C73)[($version)]($style) "
symbol = " "
style = "#685742"

[vagrant]
format = "[$symbol](#4173B7)[($version)]($style) "
symbol = " "
style = "#685742"

[vala]
format = "[$symbol](#99405C)[($version)]($style) "
symbol = " "
style = "#685742"

[verilog]
format = "[$symbol](#286887)[($version)]($style) "
symbol = "󰍛 "
style = "#685742"

[vlang]
format = "[$symbol](#86AACB)[($version)]($style) "
symbol = "󰍛 "
style = "#685742"

[zig]
format = "[$symbol](#DF9169)[($version)]($style) "
symbol = " "
style = "#685742"


