{
  enable = [
    "shell.nushell"
    "shell.carapace"
    "shell.starship"
    "terminal.zellij"
    "editor.nvim"
    "files.yazi"
    "git.lazygit"
    "nix.nh"
    "security.age"
    "security.sops"
    "system.network"
    "system.git"
    "system.search"
    "system.monitoring"
    "system.container"
    "remote.ssh"
    "remote.ftp"
  ];
}
