{
  enable = [
    "shell.nushell"
    "shell.carapace"
    "shell.starship"
    "terminal.zellij"
    "editor.nvim"
    "files.yazi"
    "git.lazygit"
    "nix.nh"
    "security.age"
    "kernel.network"
    "git.code"
    "kernel.search"
    "kernel.monitoring"
    "kernel.container"
    "remote.ssh"
    "remote.ftp"
  ];
}
