{
  themesLib,
  themeName,
  checkHelpers,
  ...
}:

let
  t = themesLib.get themeName;
  p = t.palette;
  inherit (checkHelpers) requireInfix require;
in
[
  {
    path = "domains/terminal/tmux/config/tmux.conf";
    text = ''
      # tmux config — generated by angst

      set -g default-terminal "tmux-256color"
      set -ga terminal-overrides ",*256col*:Tc"
      set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

      set -g status-style "bg=#${p.surface.variant},fg=#${t.safe.foregroundOnSurfaceVariant}"
      set -g status-left ""
      set -g status-right "#[bg=#${p.surface.variant},fg=#${t.safe.foregroundOnSurfaceVariant}] %H:%M "
      set -g status-right-length 100
      set -g status-left-length 100
      set -g status-interval 5

      set -g window-status-current-style "bg=#${p.accent.base},fg=#${p.background.base},bold"
      set -g window-status-style "bg=#${p.surface.variant},fg=#${t.safe.foregroundOnSurfaceVariant}"
      set -g window-status-format " #I:#W "
      set -g window-status-current-format " #I:#W "

      set -g pane-border-style "fg=#${p.surface.variant}"
      set -g pane-active-border-style "fg=#${p.accent.base}"

      set -g message-style "bg=#${p.surface.variant},fg=#${t.safe.foregroundOnSurfaceVariant}"
      set -g message-command-style "bg=#${p.surface.variant},fg=#${t.safe.foregroundOnSurfaceVariant}"

      set -g mode-style "bg=#${p.accent.variant},fg=#${t.safe.foregroundOnAccentVariant}"

      set -g mouse on
      set -g history-limit 50000
      set -g base-index 1
      set -g renumber-windows on
      set -g escape-time 10
      set -g detach-on-destroy off

      bind -n M-Left previous-window
      bind -n M-Right next-window
      bind '"' split-window -v -c "#{pane_current_path}"
      bind % split-window -h -c "#{pane_current_path}"
    '';
    checks = [
      (requireInfix ''#${p.surface.variant}'' "tmux status should render ${themeName} surface.variant")
      (requireInfix ''#${p.accent.base}'' "tmux active window should render ${themeName} accent.base")
      (require (
        p.surface.variant != p.accent.base
      ) "tmux status and active window must differ in ${themeName}")
    ];
  }
]
