{
  lib,
  themesLib,
  themeName,
  monitors,
  ...
}:

let
  t = themesLib.get themeName;
  p = t.palette;
  m = monitors.primary or {};
in
[
  {
    path = "domains/session/x11/config/xinitrc";
    text = ''
      #!/bin/sh

      # X11 session autostart — generated by angst

      ${lib.optionalString (m ? name && m ? resolution) ''
        xrandr --output ${m.name} \
          --mode ${m.resolution} \
          --rate ${toString (m.refreshRate or 60)} \
          --pos ${m.position or "0x0"}
      ''}

      hsetroot -solid "#${p.background.base}"

      exec i3
    '';
  }
]
